name: RARE
channels:
  - anaconda
  - defaults
dependencies:
  - cairo=1.14.12
  - certifi=2019.11.28
  - cpuonly=1.0
  - ffmpeg=4.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - opencv=3.4.2
  - openssl=1.1.1
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - py-opencv=3.4.2

  - pip:
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - pycparser==2.19
    - pyglet==1.4.10
    - pygments==2.6.1
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - scipy==1.4.1
    - pyserial==3.5.0
    
